'use client'

import { useState } from 'react'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import {
  useTeacherSummary,
  useInterventionPlan,
  useRemedialLesson,
} from '@/lib/hooks/use-impact'

type SummaryType = 'teacher' | 'intervention' | 'remedial'

interface AISummaryPanelProps {
  assessmentId: string
}

/**
 * AISummaryPanel — displays AI-generated summaries for assessment analytics.
 *
 * Features:
 * - Generate teacher summary
 * - Generate intervention plan
 * - Generate remedial lesson outline
 * - Graceful fallback if AI fails
 * - Hides provider/model details from UI
 */
export function AISummaryPanel({ assessmentId }: AISummaryPanelProps) {
  const [activeTab, setActiveTab] = useState<SummaryType>('teacher')

  const { data: teacherSummary, isLoading: teacherLoading, error: teacherError } =
    useTeacherSummary(assessmentId)
  const { data: interventionPlan, isLoading: interventionLoading, error: interventionError } =
    useInterventionPlan(assessmentId)
  const { data: remedialLesson, isLoading: remedialLoading, error: remedialError } =
    useRemedialLesson(assessmentId)

  const tabs: { id: SummaryType; label: string; icon: string }[] = [
    { id: 'teacher', label: 'Teacher Summary', icon: '📝' },
    { id: 'intervention', label: 'Intervention Plan', icon: '🎯' },
    { id: 'remedial', label: 'Remedial Lesson', icon: '📚' },
  ]

  return (
    <div className="mt-6">
      <h3 className="text-lg font-semibold text-slate-900 mb-4">AI-Generated Insights</h3>
      <p className="text-sm text-slate-600 mb-4">
        These summaries are generated by AI based on the deterministic analytics above.
        Always refer to the numbers above as the source of truth.
      </p>

      {/* Tabs */}
      <div className="border-b border-slate-200 mb-4">
        <nav className="flex gap-4">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`py-2 px-1 border-b-2 font-medium text-sm transition-colors ${
                activeTab === tab.id
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
              }`}
            >
              <span className="mr-2">{tab.icon}</span>
              {tab.label}
            </button>
          ))}
        </nav>
      </div>

      {/* Content */}
      <div className="bg-slate-50 rounded-lg p-4">
        {activeTab === 'teacher' && (
          <TeacherSummaryContent
            summary={teacherSummary}
            isLoading={teacherLoading}
            error={teacherError}
          />
        )}

        {activeTab === 'intervention' && (
          <InterventionPlanContent
            plan={interventionPlan}
            isLoading={interventionLoading}
            error={interventionError}
          />
        )}

        {activeTab === 'remedial' && (
          <RemedialLessonContent
            lesson={remedialLesson}
            isLoading={remedialLoading}
            error={remedialError}
          />
        )}
      </div>
    </div>
  )
}

// =========================================================================
// Content Components
// =========================================================================

function TeacherSummaryContent({
  summary,
  isLoading,
  error,
}: {
  summary: any
  isLoading: boolean
  error: any
}) {
  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-8">
        <LoadingSpinner />
        <span className="ml-3 text-slate-600">Generating teacher summary...</span>
      </div>
    )
  }

  if (error) {
    return (
      <div className="text-center py-8">
        <p className="text-amber-600 mb-2">Unable to generate AI summary</p>
        <p className="text-sm text-slate-600">
          Please check the analytics data above for assessment insights.
        </p>
      </div>
    )
  }

  if (!summary) {
    return (
      <div className="text-center py-8">
        <p className="text-slate-600">
          Click to generate a teacher summary based on the assessment analytics.
        </p>
      </div>
    )
  }

  return (
    <div>
      {summary.source === 'fallback' && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
          <p className="text-sm text-amber-800">
            AI summary unavailable. Showing fallback message.
          </p>
        </div>
      )}

      <div className="prose prose-sm max-w-none">
        <div className="whitespace-pre-wrap text-slate-800">{summary.summary}</div>
      </div>

      {summary.revision_sequence && (
        <div className="mt-4 pt-4 border-t border-slate-200">
          <h4 className="font-medium text-slate-900 mb-2">Suggested Revision Sequence</h4>
          <div className="whitespace-pre-wrap text-sm text-slate-700">
            {summary.revision_sequence}
          </div>
        </div>
      )}

      <div className="mt-4 text-xs text-slate-500">
        Source: {summary.source === 'ai-generated' ? 'AI-generated' : 'Fallback'}
      </div>
    </div>
  )
}

function InterventionPlanContent({
  plan,
  isLoading,
  error,
}: {
  plan: any
  isLoading: boolean
  error: any
}) {
  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-8">
        <LoadingSpinner />
        <span className="ml-3 text-slate-600">Generating intervention plan...</span>
      </div>
    )
  }

  if (error) {
    return (
      <div className="text-center py-8">
        <p className="text-amber-600 mb-2">Unable to generate intervention plan</p>
        <p className="text-sm text-slate-600">
          Please review the interventions section above for recommended actions.
        </p>
      </div>
    )
  }

  if (!plan) {
    return (
      <div className="text-center py-8">
        <p className="text-slate-600">
          Click to generate a structured intervention plan.
        </p>
      </div>
    )
  }

  return (
    <div>
      {plan.source === 'fallback' && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
          <p className="text-sm text-amber-800">
            AI intervention plan unavailable. Showing fallback message.
          </p>
        </div>
      )}

      <div className="prose prose-sm max-w-none">
        <div className="whitespace-pre-wrap text-slate-800">{plan.plan}</div>
      </div>

      <div className="mt-4 text-xs text-slate-500">
        Source: {plan.source === 'ai-generated' ? 'AI-generated' : 'Fallback'}
      </div>
    </div>
  )
}

function RemedialLessonContent({
  lesson,
  isLoading,
  error,
}: {
  lesson: any
  isLoading: boolean
  error: any
}) {
  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-8">
        <LoadingSpinner />
        <span className="ml-3 text-slate-600">Generating remedial lesson...</span>
      </div>
    )
  }

  if (error) {
    return (
      <div className="text-center py-8">
        <p className="text-amber-600 mb-2">Unable to generate remedial lesson</p>
        <p className="text-sm text-slate-600">
          Please review the weak topics above to plan your remedial activities.
        </p>
      </div>
    )
  }

  if (!lesson) {
    return (
      <div className="text-center py-8">
        <p className="text-slate-600">
          Click to generate a remedial lesson outline and mini-test idea.
        </p>
      </div>
    )
  }

  return (
    <div>
      {lesson.source === 'fallback' && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
          <p className="text-sm text-amber-800">
            AI remedial lesson unavailable. Showing fallback message.
          </p>
        </div>
      )}

      <div className="prose prose-sm max-w-none">
        <div className="whitespace-pre-wrap text-slate-800">{lesson.outline}</div>
      </div>

      {lesson.mini_test_idea && (
        <div className="mt-4 pt-4 border-t border-slate-200">
          <h4 className="font-medium text-slate-900 mb-2">Follow-up Mini-Test Idea</h4>
          <div className="whitespace-pre-wrap text-sm text-slate-700">
            {lesson.mini_test_idea}
          </div>
        </div>
      )}

      <div className="mt-4 text-xs text-slate-500">
        Source: {lesson.source === 'ai-generated' ? 'AI-generated' : 'Fallback'}
      </div>
    </div>
  )
}
