import { FileText } from 'lucide-react'
import { PageHeader, PrimaryAction, SecondaryAction, StatusBadge } from '@/components/impact/ProductUI'
import { getSeededAssessmentReport, getSeededSchoolDashboard, SEEDED_ASSESSMENTS, SEEDED_CLASSES, SEEDED_SCHOOLS, SEEDED_SUBJECTS } from '@/lib/impact/demo-data'

export default function ReportsPanel() {
  return <div><PageHeader eyebrow="Evidence exports" title="Reports" description="Open print-friendly school and assessment reports. Every report preserves its source notes, limitations and demonstration-data disclosure." />
    <section className="mb-8"><h2 className="text-lg font-black text-[var(--text-primary)]">School reports</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Aggregated class, subject, topic and intervention evidence.</p><div className="mt-4 grid gap-4 lg:grid-cols-3">{SEEDED_SCHOOLS.schools.map((school) => { const dashboard = getSeededSchoolDashboard(school.id); return <article key={school.id} className="rounded-[20px] border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-5"><FileText aria-hidden="true" className="h-5 w-5 text-[var(--accent-primary)]" /><h3 className="mt-4 text-base font-black text-[var(--text-primary)]">{school.name}</h3><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">{dashboard?.total_classes} classes · {dashboard?.total_learners_assessed} learners assessed · {dashboard?.overall_pass_rate}% pass rate</p><div className="mt-5"><PrimaryAction href={`/impact/schools/${school.id}/report`}>Open school report</PrimaryAction></div></article> })}</div></section>
    <section><h2 className="text-lg font-black text-[var(--text-primary)]">Assessment reports</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Question, topic, learner-support and deterministic intervention evidence.</p><div className="mt-4 space-y-3">{SEEDED_ASSESSMENTS.assessments.map((assessment) => { const report = getSeededAssessmentReport(assessment.id); const cls = SEEDED_CLASSES.class_groups.find((item) => item.id === assessment.class_group_id); const school = SEEDED_SCHOOLS.schools.find((item) => item.id === assessment.school_id); const subject = SEEDED_SUBJECTS.subjects.find((item) => item.id === assessment.subject_id); return <article key={assessment.id} className="grid gap-4 rounded-[20px] border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-5 md:grid-cols-[1.3fr_.8fr_.6fr_auto] md:items-center"><div><h3 className="text-sm font-black text-[var(--text-primary)]">{assessment.title}</h3><p className="mt-1 text-xs text-[var(--text-secondary)]">{school?.name} · {cls?.name} · {subject?.name}</p></div><div><p className="text-[10px] font-black uppercase tracking-[0.09em] text-[var(--text-secondary)]">Evidence</p><p className="mt-1 text-sm font-bold text-[var(--text-primary)]">{report?.questions.length} questions · {report?.learners.length} learners</p></div><StatusBadge tone="attention">{report?.analytics.weak_topics.length ?? 0} topics to review</StatusBadge><SecondaryAction href={`/impact/assessments/${assessment.id}/report`}>Open report</SecondaryAction></article> })}</div></section>
  </div>
}
