import { BarChart3, Building2, ClipboardCheck, GraduationCap, ShieldCheck, Target, UsersRound } from 'lucide-react'
import { MetricCard, PageHeader, ProgressBar, SectionCard, StatusBadge } from '@/components/impact/ProductUI'
import { getCanonicalDemoStats, getSeededSchoolDashboard, SEEDED_SCHOOLS } from '@/lib/impact/demo-data'
import { STAKEHOLDER_DEMO_DISCLOSURE } from '@/lib/impact/product-navigation'

export default function StakeholderPanel() {
  const stats = getCanonicalDemoStats()
  return <div className="space-y-6"><PageHeader eyebrow="Stakeholder demonstration" title="Aggregated school intelligence" description="A structured view of how school leaders and programme stakeholders could review learning evidence while retaining source context and limitations." />
    <div className="rounded-xl border border-[var(--accent-primary)]/30 bg-[var(--accent-primary)]/10 p-5" role="note"><div className="flex items-start gap-3"><ShieldCheck aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0 text-[var(--accent-primary)]" /><div><h2 className="text-sm font-black text-[var(--accent-primary)]">Illustrative presentation only</h2><p className="mt-1 text-sm leading-6 text-[var(--accent-primary)]">{STAKEHOLDER_DEMO_DISCLOSURE}</p></div></div></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="Schools" value={stats.schools} detail="Seeded institutions" icon={Building2} /><MetricCard label="Classes" value={stats.classes} detail="Across the demonstration" icon={GraduationCap} tone="blue" /><MetricCard label="Learners assessed" value={stats.learners} detail="Anonymous codes" icon={UsersRound} tone="violet" /><MetricCard label="Assessments" value={stats.assessments} detail="Teacher-marked" icon={ClipboardCheck} tone="teal" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><SectionCard title="School comparison" description="Seeded school-level pass rates with direct access to source reports."><div className="space-y-5">{SEEDED_SCHOOLS.schools.map((school) => { const dashboard = getSeededSchoolDashboard(school.id)!; return <div key={school.id}><div className="mb-2 flex items-center justify-between gap-4"><div><a href={`/impact/schools/${school.id}`} className="text-sm font-black text-[var(--text-primary)] hover:text-[var(--accent-primary)]">{school.name}</a><p className="mt-1 text-xs text-[var(--text-secondary)]">{dashboard.total_classes} classes · {dashboard.total_learners_assessed} learners</p></div><StatusBadge tone={dashboard.overall_pass_rate >= 60 ? 'success' : 'attention'}>{dashboard.overall_pass_rate >= 60 ? 'Monitoring' : 'Teacher review'}</StatusBadge></div><ProgressBar label="Pass rate" value={dashboard.overall_pass_rate} /></div> })}</div></SectionCard>
      <SectionCard title="Evidence priorities" description="Aggregate indicators do not replace school-level context."><div className="space-y-4"><div className="rounded-xl bg-[var(--accent-warning)]/10 p-4"><BarChart3 aria-hidden="true" className="h-5 w-5 text-[var(--accent-warning)]" /><p className="mt-3 text-2xl font-black text-[var(--accent-warning)]">{stats.weakTopics}</p><p className="text-xs font-bold text-[var(--accent-warning)]">Topics needing attention</p></div><div className="rounded-xl bg-[var(--accent-primary)]/10 p-4"><UsersRound aria-hidden="true" className="h-5 w-5 text-[var(--accent-primary)]" /><p className="mt-3 text-2xl font-black text-[var(--accent-primary)]">{stats.learnerSupportSignals}</p><p className="text-xs font-bold text-[var(--accent-primary)]">Learner-support signals requiring teacher verification</p></div><div className="rounded-xl bg-[var(--accent-primary)]/10 p-4"><Target aria-hidden="true" className="h-5 w-5 text-[var(--accent-primary)]" /><p className="mt-3 text-2xl font-black text-[var(--accent-primary)]">{stats.activeInterventions}</p><p className="text-xs font-bold text-[var(--accent-primary)]">Active teacher-led interventions</p></div></div></SectionCard></div>
    <SectionCard title="Source and limitations" description="What stakeholders should understand before interpreting this view."><div className="grid gap-3 md:grid-cols-3">{[['Source', 'Six seeded teacher-marked assessments with 39 mapped questions and 1,166 mark data points.'], ['Appropriate use', 'Illustrate school-level evidence workflows and questions for a future pilot.'], ['Not evidence of', 'Verified pilot outcomes, causal impact, production ingestion, Ministry integration or national deployment.']].map(([title, body]) => <div key={title} className="rounded-xl bg-[var(--bg-surface-raised)] p-4"><h3 className="text-sm font-black text-[var(--text-primary)]">{title}</h3><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">{body}</p></div>)}</div></SectionCard>
  </div>
}
