import { FileText, Printer } from 'lucide-react'
import { PageHeader, StatusBadge } from '@/components/impact/ProductUI'
import { getSeededAssessmentReport, getSeededSchoolDashboard, SEEDED_ASSESSMENTS, SEEDED_CLASSES, SEEDED_SCHOOLS, SEEDED_SUBJECTS } from '@/lib/impact/demo-data'

export default function ReportsPage() {
  return <div><PageHeader eyebrow="Evidence exports" title="Reports" description="Open print-friendly school and assessment reports. Every report preserves its source notes, limitations and demonstration-data disclosure." />
    <section className="mb-8"><h2 className="text-lg font-black text-slate-900">School reports</h2><p className="mt-1 text-sm text-slate-500">Aggregated class, subject, topic and intervention evidence.</p><div className="mt-4 grid gap-4 lg:grid-cols-3">{SEEDED_SCHOOLS.schools.map((school) => { const dashboard = getSeededSchoolDashboard(school.id); return <article key={school.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_3px_rgba(2,6,23,0.06)]"><FileText aria-hidden="true" className="h-5 w-5 text-cyan-600" /><h3 className="mt-4 text-base font-black text-slate-900">{school.name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{dashboard?.total_classes} classes · {dashboard?.total_learners_assessed} learners assessed · {dashboard?.overall_pass_rate}% pass rate</p><a href={`/impact/schools/${school.id}/report`} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-2xl bg-[#f5c542] px-4 text-sm font-extrabold text-[#073b4c] shadow-sm hover:bg-[#eab82d]"><Printer aria-hidden="true" className="h-4 w-4" />Open school report</a></article> })}</div></section>
    <section><h2 className="text-lg font-black text-slate-900">Assessment reports</h2><p className="mt-1 text-sm text-slate-500">Question, topic, learner-support and deterministic intervention evidence.</p><div className="mt-4 space-y-3">{SEEDED_ASSESSMENTS.assessments.map((assessment) => { const report = getSeededAssessmentReport(assessment.id); const cls = SEEDED_CLASSES.class_groups.find((item) => item.id === assessment.class_group_id); const school = SEEDED_SCHOOLS.schools.find((item) => item.id === assessment.school_id); const subject = SEEDED_SUBJECTS.subjects.find((item) => item.id === assessment.subject_id); return <article key={assessment.id} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-[1.3fr_.8fr_.6fr_auto] md:items-center"><div><h3 className="text-sm font-black text-slate-900">{assessment.title}</h3><p className="mt-1 text-xs text-slate-500">{school?.name} · {cls?.name} · {subject?.name}</p></div><div><p className="text-[10px] font-black uppercase tracking-[0.09em] text-slate-500">Evidence</p><p className="mt-1 text-sm font-bold text-slate-900">{report?.questions.length} questions · {report?.learners.length} learners</p></div><StatusBadge tone="attention">{report?.analytics.weak_topics.length ?? 0} topics to review</StatusBadge><a href={`/impact/assessments/${assessment.id}/report`} className="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-200 px-4 text-sm font-bold text-slate-700 hover:bg-slate-50">Open report</a></article> })}</div></section>
  </div>
}
